import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useRef, useState } from "react";
import { SpinnerDotted } from "spinners-react";
import { useDoubleTap } from "use-double-tap";

export default function Home() {
  const [image, setImage] = useState(null);
  const [loading, setLoading] = useState(false);
  const pick = useRef(null);
  const bind = useDoubleTap((e) => {
    pick.current.click();
  });

  const handleChange = (e) => {
    console.log(e.dataTransfer.files[0]);
    setImage("")
    if (e) {
      const reader = new FileReader();
      reader.readAsDataURL(e.dataTransfer.files[0]);
      reader.addEventListener("load", async() => {
        // setImage(reader.result);

        var data = new FormData();
        data.append("image_url", reader.result);

        var xhr = new XMLHttpRequest();
        xhr.withCredentials = false;

        xhr.addEventListener("readystatechange", function () {
          if (this.readyState === 4) {
            setLoading(false);
            setImage(JSON.parse(this.responseText).url)
            console.log(JSON.parse(this.responseText).url);
          }
        });

        xhr.open("POST", "https://api.removal.ai/3.0/remove");
        xhr.setRequestHeader("Rm-Token", "63f28eac92e979.96226787");
        
        await xhr.send(data);
        setLoading(true)
      });
    }
    //62fea7edaa2822.00733813
  };
  const handlePick = (e) => {
    setImage("")
    if (e) {
      const reader = new FileReader();
      reader.readAsDataURL(e.target.files[0]);
      reader.addEventListener("load", async () => {

        var data = new FormData();
        data.append("image_url", reader.result);

        var xhr = new XMLHttpRequest();
        xhr.withCredentials = false;

        xhr.addEventListener("readystatechange", function () {
          if (this.readyState === 4) {
            setLoading(false);
            setImage(JSON.parse(this.responseText).url)
            console.log(JSON.parse(this.responseText).url);
          }
        });

        xhr.open("POST", "https://api.removal.ai/3.0/remove");
        xhr.setRequestHeader("Rm-Token", "63f28eac92e979.96226787");
        
        await xhr.send(data);
        setLoading(true)
      });
    }
    //62fea7edaa2822.00733813
  };
  return (
    <>
      <Head>
        <title>BG-Remover</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div
        onDrop={(e) => {
          e.preventDefault();
          if (
            e.dataTransfer.files[0].type === "image/png" ||
            e.dataTransfer.files[0].type === "image/jpeg"
          ) {
            handleChange(e);
          }
        }}
        onDragLeave={(e) => {
          e.preventDefault();
        }}
        onDragOver={(e) => {
          e.preventDefault();
        }}
        {...bind}
        className={styles.full_page}
      >
        <h1>Drop x Remove Bg</h1>
        <p>Drag and drop file or Double tab on screen to upload photo!!</p>
        <input
          ref={pick}
          type="file"
          onChange={(e) => handlePick(e)}
          accept="image/*"
        />
        <div style={{padding:"1.5rem 0"}}>
          <SpinnerDotted speed={160} size={60} color="#fff" enabled={loading} />
        </div>
        <div className={styles.img}>
          <img src={image} alt="" />
          <p>{loading && "Please wait!! 😊"}{image === null && "Lets test out with some images!! 😊"} {image && image.length > 0 && "Here's your image, you can select another!! 😊"}</p>
        </div>
      </div>
    </>
  );
}
